sm7125-common: Wfd: add missing dependencies
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
java.lang.UnsatisfiedLinkError: dlopen failed: library "libdisplayconfig.so" not found: needed by /system/lib64/libwfdcommonutils.so in namespace classloader-namespace-shared